# NumPy Упражнения

Теперь, когда мы узнали о NumPy, давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы более сложные вопросы.

#### Импорт NumPy как np

In [ ]:
import numpy as np

#### Создание массива из 10 нулей

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Создайте массив из 10 единиц

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Создайте массив из 10 пятерок

In [ ]:
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Создадим массив целых чисел от 10 до 50

In [ ]:
np.arange(10, 51, 1, dtype=int)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Создадим массив из всех четных целых чисел от 10 до 50

In [ ]:
np.arange(10, 51, 2, dtype=int)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Создание матрицы 3x3 со значениями в диапазоне от 0 до 8¶

In [81]:
np.random.randint(0, 9, (3, 3))

array([[5, 7, 3],
       [8, 6, 3],
       [1, 8, 7]])

#### Создание единичной матрицы 3x3

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
np.random.rand()

0.5624982984873549

#### Используйте NumPy для создания массива из 25 случайных чисел, отобранных из стандартного нормального распределения

In [ ]:
np.random.normal(loc=0, scale=1, size=25)

array([-0.59417931, -0.35876612, -0.08922799,  0.97459032, -0.31833442,
        0.26567083,  1.52241165,  0.37181891, -0.17962687, -0.6917677 ,
        0.76142474,  1.08231832,  0.59561599, -0.92945917,  1.58502182,
        2.60797727, -0.08976257, -0.95090625, -0.54905027, -1.81233982,
        0.84808419,  2.09455374,  1.08791174, -0.70819074,  0.39057395])

#### Создайте матрицу 10 на 10 из равномерно удаленных точек от 0.1 до 1( см linspace):

In [ ]:
print(np.linspace(0.1, 1, 100).reshape(10, 10)) # как просится в задании (начиная с 0.1)
print()
np.linspace(0.01, 1, 100).reshape(10, 10) # как показывалось ниже (начиная с 0.01)

[[0.1        0.10909091 0.11818182 0.12727273 0.13636364 0.14545455
  0.15454545 0.16363636 0.17272727 0.18181818]
 [0.19090909 0.2        0.20909091 0.21818182 0.22727273 0.23636364
  0.24545455 0.25454545 0.26363636 0.27272727]
 [0.28181818 0.29090909 0.3        0.30909091 0.31818182 0.32727273
  0.33636364 0.34545455 0.35454545 0.36363636]
 [0.37272727 0.38181818 0.39090909 0.4        0.40909091 0.41818182
  0.42727273 0.43636364 0.44545455 0.45454545]
 [0.46363636 0.47272727 0.48181818 0.49090909 0.5        0.50909091
  0.51818182 0.52727273 0.53636364 0.54545455]
 [0.55454545 0.56363636 0.57272727 0.58181818 0.59090909 0.6
  0.60909091 0.61818182 0.62727273 0.63636364]
 [0.64545455 0.65454545 0.66363636 0.67272727 0.68181818 0.69090909
  0.7        0.70909091 0.71818182 0.72727273]
 [0.73636364 0.74545455 0.75454545 0.76363636 0.77272727 0.78181818
  0.79090909 0.8        0.80909091 0.81818182]
 [0.82727273 0.83636364 0.84545455 0.85454545 0.86363636 0.87272727
  0.88181818 0.8909

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Создайте массив из 20 линейно удаленных точек от 0 до 1( см linspace):

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Индексы

В матрице

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Напишите код таким образом, чтоб появился вывод на экран

In [ ]:
# выведите

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# впишите код
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# выведите

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# впишите код
mat[-3:, -4:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# выведите

20

In [ ]:
# впишите код
mat[3, 4]

np.int64(20)

In [ ]:
# выведите

20

In [ ]:
# впишите код
# отличный от кода выше
mat[-2, -1]

np.int64(20)

In [ ]:
# выведите

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# впишите код
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# выведите

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# впишите код
mat[:-2, -4:-3]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# выведите

array([[21, 22, 23, 24, 25]])

In [ ]:
# впишите код
mat[4:, :]

array([[21, 22, 23, 24, 25]])

In [ ]:
# выведите

array([21, 22, 23, 24, 25])

In [ ]:
# впишите код
mat[-1:, :]

array([[21, 22, 23, 24, 25]])

In [ ]:
# выведите

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# впишите код
mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# выведите

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# впишите код
mat[-2:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Теперь сделайте следующее

#### Получить сумму всех значений в mat

In [ ]:
np.sum(mat)

np.int64(325)

#### Получить стандартное отклонение значений в mat (пакет Статистика)

In [84]:
np.std(mat)

np.float64(7.211102550927978)

#### Посчитайте сумму всех столбцов в mat

In [ ]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])